export const PartnerShopData = [
  {
    name: 'カードショップmagi秋葉原店',
    image: '/images/home/partnershop/list/shop1.png',
    address: '〒101-0021 東京都千代⽥区外神⽥３丁⽬１４−9, Azuma Building, 5F',
    phone: '📞 013-5930-2200',
    type: 'OFFLINE',
    link: '',
  },
  {
    name: 'magi中野ブロードウェイ店',
    image: '/images/home/partnershop/list/shop2.png',
    address: '〒164-0001 東京都中野区中野５丁目５２−１５ 2F',
    phone: '📞 013-5930-2200',
    type: 'OFFLINE',
    link: '',
  },
  {
    name: 'たいむましん',
    image: '/images/home/partnershop/list/shop3.png',
    address: '〒348-0065 埼玉県羽生市大字藤井下組171',
    phone: '📞️ 048-598-6557',
    type: 'OFFLINE',
    link: '',
  },
  {
    name: 'Cardshop Serra',
    image: '/images/home/partnershop/list/shop4.png',
    address: '〒410-0801 静岡県沼津市大手町5-7-5 つるかめ仲見世ビル4F',
    phone: '📞 055-963-2750',
    type: 'ONLINE',
    link: 'https://cardshop-serra.com',
  },
  {
    name: 'ドラグーン博多Gameスペース&cafe',
    image: '/images/home/partnershop/list/shop5.png',
    address: '博多区博多駅前１丁目３−２２ かき善ビル４階',
    phone: '📞 092-710-2292',
    type: 'OFFLINE',
    link: '',
  },
  {
    name: 'TCG専門店CANTRIP',
    image: '/images/home/partnershop/list/shop6.png',
    address: 'R八王子駅北口 徒歩3分',
    phone: '📞 080-2558-6054',
    type: 'ONLINE',
    link: 'https://cantripmtg.com/products/brgグレーディング受付代行サービス',
  },
  {
    name: '遊楽舎',
    image: '/images/home/partnershop/list/shop7.png',
    address: '〒671-0251 兵庫県姫路市花田町上原田2-1 ビッグエムワン2F',
    phone: '📞 079-240-5944',
    type: 'OFFLINE',
    link: '',
  },
  {
    name: 'BEEP Akihabara',
    image: '/images/home/partnershop/list/shop8.png',
    address: '〒348-0065 埼玉県羽生市藤井下組171',
    phone: '📞 0120-549-542',
    type: 'OFFLINE',
    link: '',
  },
  {
    name: 'GRADINGSERVICES JAPAN',
    image: '/images/home/partnershop/list/shop9.png',
    address: '博多区博多駅前１丁目３−２２ かき善ビル４階',
    phone: '📞 092-710-2292',
    type: 'ONLINE',
    link: 'https://gradingservices.jp',
  },
] as const;

export type PartnerShopDataType = (typeof PartnerShopData)[number];
