name: Deploy japan production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_JAPAN_PRODUCTION }}
on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  deploy:
    uses: ./.github/workflows/common.yml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_JAPAN_PRODUCTION }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
